# Generated by Django 5.1.15 on 2026-04-07 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новий'), ('confirmed', 'Підтверджений'), ('paid', 'Оплачений'), ('shipped', 'Відправлений'), ('delivered', 'Доставлений'), ('cancelled', 'Скасований')], default='new', max_length=20, verbose_name='Статус')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('delivery_method', models.CharField(choices=[('nova_poshta', 'Нова Пошта'), ('ukrposhta', 'Укрпошта'), ('delivery', 'Delivery'), ('meest', 'Meest'), ('rozetka', 'Rozetka Delivery'), ('pickup', 'Самовивіз')], max_length=20, verbose_name='Доставка')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Адреса доставки')),
                ('nova_poshta_city', models.CharField(blank=True, max_length=255, verbose_name='Місто НП')),
                ('nova_poshta_warehouse', models.CharField(blank=True, max_length=255, verbose_name='Відділення НП')),
                ('payment_method', models.CharField(choices=[('card_manual', 'Оплата на картку'), ('liqpay', 'LiqPay'), ('monobank', 'MonoBank'), ('cod', 'Накладений платіж')], max_length=20, verbose_name='Оплата')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сума')),
                ('tracking_number', models.CharField(blank=True, max_length=50, verbose_name='ТТН')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500, verbose_name='Назва товару')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
            },
        ),
    ]
