# Generated by Django 5.1.15 on 2026-04-07 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('liqpay', 'LiqPay'), ('monobank', 'MonoBank'), ('card_manual', 'На картку'), ('cod', 'Накладений платіж')], max_length=20, verbose_name='Провайдер')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('success', 'Успішно'), ('failed', 'Помилка'), ('refunded', 'Повернено')], default='pending', max_length=20, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума')),
                ('external_id', models.CharField(blank=True, max_length=255, verbose_name='Зовнішній ID')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Відповідь API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Платіж',
                'verbose_name_plural': 'Платежі',
            },
        ),
    ]
