# Generated by Django 5.1.15 on 2026-04-07 10:46

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Зображення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('original_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='ID з імпорту')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Батьківська категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='ID пропозиції')),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Артикул (SKU)')),
                ('name', models.CharField(max_length=500, verbose_name='Назва')),
                ('slug', models.SlugField(allow_unicode=True, max_length=500, unique=True, verbose_name='Slug')),
                ('brand', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Бренд')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Роздрібна ціна')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стара ціна')),
                ('currency', models.CharField(default='UAH', max_length=5, verbose_name='Валюта')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наявності')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Хіт продажів')),
                ('box_quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість в ящику')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500, verbose_name='URL зображення')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Локальне зображення')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Зображення товару',
                'verbose_name_plural': 'Зображення товарів',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Параметр')),
                ('value', models.CharField(max_length=500, verbose_name='Значення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='WholesalePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(verbose_name='Мін. кількість')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Гуртова ціна')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_prices', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Гуртова ціна',
                'verbose_name_plural': 'Гуртові ціни',
                'ordering': ['min_quantity'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available', '-created_at'], name='catalog_pro_is_avai_6be515_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_available'], name='catalog_pro_categor_ac86d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wholesaleprice',
            unique_together={('product', 'min_quantity')},
        ),
    ]
