# Generated by Django 5.2.13 on 2026-05-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_staticpage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_1', models.CharField(blank=True, max_length=20, verbose_name='Телефон 1')),
                ('phone_2', models.CharField(blank=True, max_length=20, verbose_name='Телефон 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('shop_name', models.CharField(default='LMM', max_length=255, verbose_name='Назва магазину')),
                ('shop_tagline', models.CharField(default='Інтернет-магазин низьких цін', max_length=255, verbose_name='Слоган')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
