# Generated by Django 5.1.15 on 2026-04-07 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug')),
                ('post_type', models.CharField(choices=[('article', 'Стаття'), ('promo', 'Акція'), ('video', 'Відеоогляд'), ('news', 'Новина')], default='article', max_length=20, verbose_name='Тип')),
                ('content', models.TextField(verbose_name='Контент')),
                ('image', models.ImageField(blank=True, upload_to='blog/', verbose_name='Зображення')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Публікація',
                'verbose_name_plural': 'Публікації',
                'ordering': ['-created_at'],
            },
        ),
    ]
